### ISSUE TITLE
Enhancement: Option to control time increments

### ISSUE THREAD

**Issue by rginnow** [makzumi/laravel-calendar#3]
I'd like to suggest the option of allowing the developer to choose how often to show events - 5, 10, 15, 20, 30, 1, or 2 hours - from the start time of day to end time.

Ex:
`$cal->setStartEndHours(7,21);`
`$cal->setHowOften('+1 hour'); // could be '+5 minutes', '+30 minutes', etc.`

**Comment by Donny5300** [comment]
This one is solved already
